/*
 * Copyright (c) 2026 YOUR NAME HERE <YOUR EMAIL HERE>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

/*
 * Support for reading Git "commit-graph" files, as documented in Git's
 * own Documentation/gitformat-commit-graph.adoc. This is an independent
 * implementation written directly from that format specification; it
 * shares no code with Git's commit-graph.c, which is GPL-licensed and
 * therefore unsuitable as a source to copy or adapt from.
 *
 * got never writes commit-graph files. This code only ever reads a
 * file which is assumed to have been generated by "git commit-graph
 * write" (or equivalent), and treats it purely as an optional,
 * disposable accelerator: if the file is missing, truncated, of an
 * unsupported version, or otherwise unusable, callers fall back to
 * deriving the same information from commit objects directly.
 *
 * Only single-file, non-chained commit-graphs are supported, i.e.
 * $GIT_DIR/objects/info/commit-graph. Split commit-graph chains
 * (the files under objects/info/commit-graphs/), Bloom filter chunks
 * (BIDX/BDAT), and the "generation data" v2 chunks (GDA2/GDO2) are
 * not implemented.
 * None of these are required to obtain correct parent, tree, and
 * generation-number (v1) information for every commit recorded in
 * a single-file commit-graph.
 */

#define GOT_CGRAPH_PATH		"objects/info/commit-graph"

struct got_cgraph;

/*
 * Attempt to open a commit-graph file. The directory file descriptor
 * must reference a Git directory (i.e. it is used together with the
 * relative path GOT_CGRAPH_PATH). The hash algorithm must match the
 * algorithm used by the repository; a commit-graph file recorded with
 * a different hash algorithm is rejected.
 *
 * If the file does not exist, GOT_ERR_NOT_GIT_REPO... (ENOENT) is
 * returned via got_error_from_errno2() as usual; callers which treat
 * a missing commit-graph file as "feature unavailable" should check
 * for errno == ENOENT specifically (see got_cgraph_try_open() below
 * for a convenience wrapper which already does this).
 */
const struct got_error *got_cgraph_open(struct got_cgraph **, int,
    enum got_hash_algorithm);

/*
 * Like got_cgraph_open(), but never fails on account of the file being
 * missing or unusable: *cgraph is simply left NULL in that case. Only
 * I/O errors unrelated to the file's existence/format are returned.
 */
const struct got_error *got_cgraph_try_open(struct got_cgraph **, int,
    enum got_hash_algorithm);

void got_cgraph_close(struct got_cgraph *);

/* Look up a commit by ID. Returns its row index, or -1 if not present. */
int got_cgraph_find(struct got_cgraph *, struct got_object_id *);

/* Fetch the recorded generation number (topological level) of a commit. */
uint32_t got_cgraph_get_generation(struct got_cgraph *, int);

/* Fetch the recorded committer time of a commit. */
time_t got_cgraph_get_committer_time(struct got_cgraph *, int);

/* Fetch the recorded root tree ID of a commit. */
void got_cgraph_get_tree_id(struct got_cgraph *, int,
    struct got_object_id *);

/*
 * Append the parent IDs of a commit, in parent order, to the tail of
 * the given queue. Handles octopus merges (more than two parents) via
 * the Extra Edge List chunk.
 */
const struct got_error *got_cgraph_get_parent_ids(struct got_cgraph *,
    int, struct got_object_id_queue *);
